name: Test

on:
  push:
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - '**.py'

jobs:
  type-check:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '*'
          cache: pip

      - name: Install the development dependencies
        run: pip install -r requirements.txt

      - name: Run typechecker
        run: pyright

  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '*'
          cache: pip

      - name: Install the development dependencies
        run: pip install -r requirements.txt

      - name: Run linter
        run: pylint --recursive=y .

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '*'
          cache: pip

      - name: Install the development dependencies
        run: pip install -r requirements.txt

      - name: Build the extension
        run: python setup.py build_ext --inplace

      - name: Run tests
        run: pytest

  install:
    runs-on: windows-latest

    steps:
      - name: Install KeyWin
        run: pip install git+https://github.com/winstxnhdw/KeyWin

      - name: Mini smoke test
        run: python -c "from keywin import keyboard; keyboard.press(0x5B, 0x44)"
