name: Test

on:
  push:
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - '**.py'

jobs:
  type-check:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1
        with:
          python-version: '*'
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Run typechecker
        run: pdm run pyright

  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1
        with:
          python-version: '*'
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Run linter
        run: pdm run pylint --ignore-paths=.venv --recursive=y .

  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Run tests
        run: pdm run pytest

  install:
    runs-on: windows-latest

    steps:
      - name: Install KeyWin
        run: pip install git+https://github.com/winstxnhdw/KeyWin

      - name: Mini smoke test
        run: python -c "from keywin import keyboard; keyboard.press(0x5B, 0x44)"
